### ISSUE TITLE
Thank you for Upgrading the Repo. But Receiving following error.

### ISSUE THREAD

**Issue by anilwarbhe** [nuxt-community/nuxt7#101]
abc@dc1:~/f7apps/nuxtapps$ npx sao@1 -u nuxt-community/nuxt7 nuxt7-app
success Downloaded repo
Usage: yarn [options]

yarn: error: no such option: --production

/home/abc/.npm/_npx/21026/lib/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in /home/abc/.sao/V1/repos/404bde14
    at ChildProcess.<anonymous> (/home/abc/.npm/_npx/21026/lib/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12) {
  __sao: true
}

**Comment by anilwarbhe** [comment]
Updated the Yarn and now it works. Thank you so much.
