### ISSUE TITLE
FATAL  No build files found in /home/user/myproject/.nuxt/dist/server

### ISSUE THREAD

**Issue by mpuz** [nuxt-community/nuxt7#125]
Can't run after build:
Ubuntu 20.04, node v12.16.2

to reproduce :
npx sao@1 -u nuxt-community/nuxt7 nuxt7-app
yarn install
yarn run -> build
yarn run -> start

``` FATAL  No build files found in /home/user/PROJECTS/myproject/.nuxt/dist/server.                                                       20:41:34
Use either `nuxt build` or `builder.build()` or start nuxt in development mode.

  Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
  at VueRenderer._ready (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4219:13)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:637:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:720:7)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                  │
   │   ✖ Nuxt Fatal Error                                                                             │
   │                                                                                                  │
   │   Error: No build files found in /home/user/PROJECTS/myproject/.nuxt/dist/server.   │
   │   Use either `nuxt build` or `builder.build()` or start nuxt in development mode.                │
   │                                                                                                  │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
```

**Comment by mpuz** [comment]
npm run generate - works, so this is only for static
