### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by robsontenorio** [nuxt-community/nuxt7#17]
FRESH INSTALL

```
npx sao nuxt-community/nuxt7 nuxt7-app

cd nuxt7-app
yarn run dev
```

ERROR

```
{ Error: Cannot find module 'framework7/scripts/build-config'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/BackupHD/Dropbox/dev/nuxt7-app/node_modules/nuxt7/lib/module.js:3:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at ModuleContainer._callee2$ (/Volumes/BackupHD/Dropbox/dev/nuxt7-app/node_modules/nuxt/lib/core/module.js:108:16)
    at tryCatch (/Volumes/BackupHD/Dropbox/dev/nuxt7-app/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Volumes/BackupHD/Dropbox/dev/nuxt7-app/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Volumes/BackupHD/Dropbox/dev/nuxt7-app/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21) code: 'MODULE_NOT_FOUND' }
```

**Comment by robsontenorio** [comment]
It seems to be a error on link provided on README.md

https://unpkg.com/framework7@2.0.1/scripts/build-config.js
