### ISSUE TITLE
Error with starter template on windows 10

### ISSUE THREAD

**Issue by pauloguerraf** [nuxt-community/nuxt7#22]
I am getting the following error when trying to creat a new app from starter template:

$ npx sao nuxt-community/nuxt7 nuxt7-app
C:\Users\paulo\AppData\Roaming\npm\node_modules\sao\bin\sao
error SyntaxError: C:\Users\paulo\.sao\repos\nuxt-community%%nuxt7\package.json: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.readPkg (C:\Users\paulo\AppData\Roaming\npm\node_modules\sao\lib\utils\index.js:68:12)
    at C:\Users\paulo\AppData\Roaming\npm\node_modules\sao\lib\index.js:93:27
    at next (native)

Any tip would be really appreciated.
Best,
Paulo

**Comment by pi0** [comment]
Hi. Sorry for inconviebces this is a known issue with F7 packaging. Will try to resolve it soon.

**Comment by pi0** [comment]
Hi. This will be fixed soon with 1.0.0 release.
