### ISSUE TITLE
"Quick Start" command fails to install starter template

### ISSUE THREAD

**Issue by nathanchase** [nuxt-community/nuxt7#42]
Running ` npx sao nuxt-community/nuxt7 nuxt7-app` in an empty folder produces the following error for me:
```
$ npx sao nuxt-community/nuxt7 nuxt7-app
npx: installed 388 in 15.201s
error SyntaxError: C:\Users\Nathan\.sao\repos\nuxt-community%%nuxt7\package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.exports.readPkg (C:\Users\Nathan\AppData\Roaming\npm-cache\_npx\4164\node_modules\sao\lib\utils\index.js:68:12)
    at C:\Users\Nathan\AppData\Roaming\npm-cache\_npx\4164\node_modules\sao\lib\index.js:94:27
    at Generator.next (<anonymous>)
```

I'm running:
node 10.9.0
npm 6.0.0
npx 6.0.0

Is there some sort of configuration I'm missing here?

**Comment by pi0** [comment]
Hi. Windows compat problem should be resolved. Please try again and ping me if still having problems. Thanks.
