### ISSUE TITLE
cannot run the app on production mode

### ISSUE THREAD

**Issue by ferchoz** [nuxt-community/nuxt7#83]
Hello i can't run the default app in production mode.
steps to reproduce:
`npx sao@1 -u nuxt-community/nuxt7 nuxt7-app`
`cd nuxt7-app`
`yarn build`
`yarn run start`

Output:
yarn run v1.17.3
$ nuxt start

 FATAL  No build files found in /nuxt7-app/.nuxt/dist/server.                                                           09:14:55
Use either `nuxt build` or `builder.build()` or start nuxt in development mode.

  Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
  at VueRenderer._ready (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4215:13)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:606:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:647:7)

   ╭────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                │
   │   ✖ Nuxt Fatal Error                                                                           │
   │                                                                                                │
   │   Error: No build files found in /nuxt7-app/.nuxt/dist/server.   │
   │   Use either `nuxt build` or `builder.build()` or start nuxt in development mode.              │
   │                                                                                                │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cip8** [comment]
I experienced a similar error when trying to start my nuxt project. 

For those that might have a similar issue, check to see if it's not caused by one of your dependencies. In my case it happened because `fibers ^5.0.0` cannot run on `node 16+` yet. So the fix for me was to temporarily **downgrade node from 16.3 to 15.14**.
